### ISSUE TITLE
Builds metrics: labels for repos & branches

### ISSUE THREAD

**Issue by Elfo404** [grafana/grafana-ci-otel-collector#28]
When generating build stats, it'd be valuable to be able to divide them by repos and branches. However, while this is not true for repos names, adding a label for each branch name may not be a viable solution due to the high cardinality this may produce.

However having the branch name as a label would greatly help in monitoring pipelines, especially when it comes to track specific release branches. We can potentially mitigate the high cardinality issue by allowing users to configure specific branches/repos for which labels should be added to generated metrics (when it makes sense).

for instance, a configuration like:

```yaml
    repos:
      # all repos listed here will get a repo label set to their actual name
      grafana/gracie:
        # same for branches
        - main
        - v10.0.x
```

would add the `repo="grafana/gracie"` label to every metric related to that repo, and `branch="main"` or `branch="v10.0.x"` when the metric is related to one of those branches. everything else can be assigned a default set of labels (such as `repo="UNTRACKED"` ) so that cardinality is kept at a minimum.

When scraping builds number for instance, with a configuration like

```yaml
repos:
  # all repos listed here will get a repo label set to their actual name
  grafana/gracie:
  # same for branches
    - main
  grafana/grafana:
    - main
    - v10.0.x
```

we could generate a query like the following
```sql
SELECT 
		build_status, 
		CASE 
			WHEN repo_slug IN ('grafana/gracie', 'grafana/grafana') THEN repo_slug
			ELSE 'other'
		END AS repo,
		CASE 
			WHEN repo_slug = 'grafana/gracie' AND build_source IN ('main') THEN build_source
			WHEN repo_slug = 'grafana/grafana' AND build_source IN ('main', 'v10.0.x') THEN build_source
			ELSE 'other'
		END AS source,
		COUNT(*) AS count
	FROM 
		builds 
	JOIN
		repos ON builds.build_repo_id  = repos.repo_id
	GROUP BY 
		build_status, 
		repo,
		source;
```
